// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module4HW3.DataModel;

#nullable disable

namespace Module4HW3.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230109185518_FillSampleData_Client_Project")]
    partial class FillSampleDataClientProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module4HW3.DataModel.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "vktrtmchshn@gmail.com",
                            FirstName = "Viktoriia",
                            LastName = "Tomchyshyn",
                            PhoneNumber = "+380978945678"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "vtmchshn@gmail.com",
                            FirstName = "Volodymyr",
                            LastName = "Tomchyshyn",
                            PhoneNumber = "+380978945600"
                        },
                        new
                        {
                            ClientId = 3,
                            Email = "anasttmchshn@gmail.com",
                            FirstName = "Anastasiia",
                            LastName = "Tomchyshyn",
                            PhoneNumber = "+380958445600"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "ihor.ant@gmail.com",
                            FirstName = "Ihor",
                            LastName = "Antoniuk",
                            PhoneNumber = "+380937890567"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "yuliakoval@gmail.com",
                            FirstName = "Yulia",
                            LastName = "Koval",
                            PhoneNumber = "+380937890533"
                        });
                });

            modelBuilder.Entity("Module4HW3.DataModel.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HiredDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LastName");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("TitleId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Module4HW3.DataModel.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeProjectId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeProjectId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real")
                        .HasColumnName("Rate");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedDate");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProject", (string)null);
                });

            modelBuilder.Entity("Module4HW3.DataModel.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfficeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("OfficeId");

                    b.ToTable("Office", (string)null);
                });

            modelBuilder.Entity("Module4HW3.DataModel.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<float>("Budjet")
                        .HasColumnType("real")
                        .HasColumnName("Budjet");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedDate");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budjet = 100000f,
                            ClientId = 1,
                            Name = "MedicalSystem",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5095)
                        },
                        new
                        {
                            ProjectId = 2,
                            Budjet = 500000f,
                            ClientId = 2,
                            Name = "CosmeticsShop",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5124)
                        },
                        new
                        {
                            ProjectId = 3,
                            Budjet = 1000000f,
                            ClientId = 2,
                            Name = "HomeShop",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5127)
                        },
                        new
                        {
                            ProjectId = 4,
                            Budjet = 200000f,
                            ClientId = 3,
                            Name = "SchoolDiary",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5129)
                        },
                        new
                        {
                            ProjectId = 5,
                            Budjet = 6000000f,
                            ClientId = 4,
                            Name = "HealthMentainer",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5132)
                        },
                        new
                        {
                            ProjectId = 6,
                            Budjet = 500000f,
                            ClientId = 5,
                            Name = "GreenShop",
                            StartedDate = new DateTime(2023, 1, 9, 21, 55, 17, 576, DateTimeKind.Local).AddTicks(5138)
                        });
                });

            modelBuilder.Entity("Module4HW3.DataModel.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TitleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("TitleId");

                    b.ToTable("Title", (string)null);
                });

            modelBuilder.Entity("Module4HW3.DataModel.Employee", b =>
                {
                    b.HasOne("Module4HW3.DataModel.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4HW3.DataModel.Title", "Title")
                        .WithMany("Employees")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Module4HW3.DataModel.EmployeeProject", b =>
                {
                    b.HasOne("Module4HW3.DataModel.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module4HW3.DataModel.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Project", b =>
                {
                    b.HasOne("Module4HW3.DataModel.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Module4HW3.DataModel.Title", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
